ZombieParty/ZombieParty/Models/ErrorViewModel.cs
namespace ZombieParty.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ZombieParty/ZombieParty/Models/Zombie.cs
namespace ZombieParty.Models
{
    public class Zombie
    {
        public string Name { get; set; }
        public string Type { get; set; }
        public int Point { get; set; }
    }
}

ZombieParty/ZombieParty/Models/ZombieType.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ZombieParty.Models
{
    public class ZombieType
    {
        public int Id { get; set; }
        [DisplayName("Type Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Type Name has to be filled.")]
        public string TypeName { get; set; }
    }
}

ZombieParty/ZombieParty/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ZombieParty.Models;

namespace ZombieParty.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ZombieParty/ZombieParty/Controllers/ZombieController.cs
using Microsoft.AspNetCore.Mvc;
using ZombieParty.Models;

namespace ZombieParty.Controllers
{
    public class ZombieController : Controller
    {
        public IActionResult Index()
        {
            this.ViewBag.MaListe = new List<Zombie>()
            {
                new Zombie(){Name= "LeChuck", Point=5, Type="Fiction",},
                new Zombie(){Name= "Lenore", Point=4, Type="Fiction",},
                new Zombie(){Name= "Draugr", Point=2, Type="Légendaire",},
                new Zombie(){Name= "Ragamuffin", Point=5, Type="Légendaire",},
                new Zombie(){Name= "Taxidermy", Point=1, Type="Légendaire",},
                new Zombie(){Name= "chien de l'enfer", Point=7, Type="Fiction",},
                new Zombie(){Name= "Avogadro", Point=9, Type="Fiction",}
            };

            return View();
        }
    }
}

ZombieParty/ZombieParty/Controllers/ZombieTypeController.cs
using Microsoft.AspNetCore.Mvc;
using ZombieParty.Models;

namespace ZombieParty.Controllers
{
    public class ZombieTypeController : Controller
    {
        public IActionResult Index()
        {
            this.ViewBag.MaListe = new List<ZombieType>()
            {
                new ZombieType(){TypeName= "Virus", Id=1},
                new ZombieType(){TypeName= "Contact", Id=2}
            };

            return View();
        }

        //GET CREATE
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        public IActionResult Create(Models.ZombieType zombieType)
        {
            if (ModelState.IsValid)
            {
                // Ajouter à la BD
            }

            return this.View(zombieType);
        }

    }
}

ZombieParty/ZombieParty/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ZombieParty/ZombieParty/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZombieParty</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ZombieParty.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/imagesLayout/tile.png" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Zombies
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Zombie" asp-action="Index">Manage Zombies</a></li>
                                <li><a class="dropdown-item" asp-controller="ZombieType" asp-action="Index">Manage Types</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                              </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ZombieParty - Mathieu Briau <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ZombieParty/ZombieParty/Views/Zombie/Index.cshtml
<div class="container p-3">
    <div class="row">
        @foreach (var item in this.ViewBag.MaListe)
        {
            <div href="#" class="card  border m-3 text-center bg-warning" style="width: 20rem; background-image: url('/images/imagesLayout/Fond.png');">
                <div class="card-body text-warning">
                    <h3> @item.Name</h3>
                    <h5> @item.Point</h5>
                </div>
            </div>
        }
    </div>
</div>

ZombieParty/ZombieParty/Views/ZombieType/Create.cshtml
@model ZombieParty.Models.ZombieType
<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">Zombie Type</h2>
            <hr />
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-2">
                        <label asp-for="TypeName"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="TypeName" class="form-control" />
                        <span asp-validation-for="TypeName" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row py-2">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back to list</a>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-4">
            </div>
        </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ZombieParty/ZombieParty/Views/ZombieType/Index.cshtml
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-10">
            <h2 class="text-primary">Zombie Type</h2>
        </div>
        <div class="col-2 text-right">
            <a class="btn btn-success" asp-action="Create">
                Create New Type
            </a>
        </div>
    </div>

    <br /><br />
    <table class="table table-bordered table-striped" style="width:100%">
        <thead class="bg-dark text-white">
            <tr>
                <th>
                    Type Name
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in this.ViewBag.MaListe)
            {
                <tr>
                    <td width="80%">@item.TypeName</td>
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a class="btn btn-warning mx-2">
                                Edit
                            </a>
                            <a class="btn btn-danger mx-2">
                                Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>